#!/usr/bin/env node

/**
 * HTML Report Screenshot Automation Tool
 * 
 * This script uses Playwright to automate viewing and capturing screenshots
 * of HTML compliance reports generated by PowerShell scripts.
 * 
 * Usage:
 *   node screenshot-report.js [options]
 * 
 * Options:
 *   --input <path>     Path to HTML file or directory (default: ./reports)
 *   --output <path>    Output directory for screenshots (default: ./screenshots)
 *   --test             Generate a sample HTML report for testing
 *   --help             Show this help message
 * 
 * Examples:
 *   node screenshot-report.js --input report.html
 *   node screenshot-report.js --input ./reports --output ./output
 *   node screenshot-report.js --test
 */

const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

// Parse command line arguments
function parseArgs() {
    const args = {
        input: './reports',
        output: './screenshots',
        test: false,
        help: false
    };

    for (let i = 2; i < process.argv.length; i++) {
        const arg = process.argv[i];
        
        if (arg === '--help' || arg === '-h') {
            args.help = true;
        } else if (arg === '--test') {
            args.test = true;
        } else if (arg === '--input' || arg === '-i') {
            if (i + 1 < process.argv.length) {
                args.input = process.argv[++i];
            } else {
                console.error('Error: --input requires a path argument');
                process.exit(1);
            }
        } else if (arg === '--output' || arg === '-o') {
            if (i + 1 < process.argv.length) {
                args.output = process.argv[++i];
            } else {
                console.error('Error: --output requires a path argument');
                process.exit(1);
            }
        }
    }

    return args;
}

// Display help message
function showHelp() {
    console.log(`
HTML Report Screenshot Automation Tool

Usage:
  node screenshot-report.js [options]

Options:
  --input <path>     Path to HTML file or directory (default: ./reports)
  --output <path>    Output directory for screenshots (default: ./screenshots)
  --test             Generate a sample HTML report for testing
  --help, -h         Show this help message

Examples:
  node screenshot-report.js --input report.html
  node screenshot-report.js --input ./reports --output ./output
  node screenshot-report.js --test
    `);
}

// Generate a sample HTML report for testing
function generateSampleReport() {
    const reportsDir = path.join(__dirname, 'reports');
    
    // Create reports directory if it doesn't exist
    if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
    }

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').substring(0, 19);
    const filename = `sample-report-${timestamp}.html`;
    const filepath = path.join(reportsDir, filename);

    const sampleHtml = `<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { background-color: #f8f9fa; padding: 20px; border-radius: 5px; margin-bottom: 20px; }
        .summary { background-color: #e3f2fd; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .success { background-color: #e8f5e8; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .error { background-color: #ffebee; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        table { border-collapse: collapse; width: 100%; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .footer { font-size: 12px; color: #666; margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; }
    </style>
</head>
<body>
    <div class="header">
        <h2>🔒 Inactive Account Lock Report</h2>
        <p><strong>Execution Date:</strong> ${new Date().toLocaleString()}</p>
        <p><strong>Mode:</strong> Sample Test Report</p>
        <p><strong>Inactivity Threshold:</strong> 90 days</p>
    </div>
    
    <div class="summary">
        <h3>📊 Summary</h3>
        <ul>
            <li><strong>Accounts Processed:</strong> 3</li>
            <li><strong>Errors Encountered:</strong> 0</li>
        </ul>
    </div>
    
    <div class="success">
        <h3>✅ Blocked Accounts</h3>
        <table>
            <tr>
                <th>Display Name</th>
                <th>User Principal Name</th>
                <th>Last Sign-In Date</th>
                <th>Days Inactive</th>
            </tr>
            <tr>
                <td>John Doe</td>
                <td>john.doe@contoso.com</td>
                <td>2024-08-15 14:23:45</td>
                <td>97</td>
            </tr>
            <tr>
                <td>Jane Smith</td>
                <td>jane.smith@contoso.com</td>
                <td>2024-07-20 09:15:33</td>
                <td>123</td>
            </tr>
            <tr>
                <td>Bob Johnson</td>
                <td>bob.johnson@contoso.com</td>
                <td>2024-06-10 16:42:18</td>
                <td>163</td>
            </tr>
        </table>
    </div>
    
    <div class="footer">
        <p>This report was automatically generated by the Inactive Account Lock automation script.</p>
        <p>For questions or concerns, please contact your IT administrator.</p>
    </div>
</body>
</html>`;

    fs.writeFileSync(filepath, sampleHtml);
    console.log(`✅ Sample report generated: ${filepath}`);
    
    return filepath;
}

// Get all HTML files from a directory
function getHtmlFiles(inputPath) {
    const htmlFiles = [];
    
    // Check if path exists first
    if (!fs.existsSync(inputPath)) {
        return htmlFiles;
    }
    
    try {
        if (fs.statSync(inputPath).isDirectory()) {
            const files = fs.readdirSync(inputPath);
            for (const file of files) {
                if (file.endsWith('.html') || file.endsWith('.htm')) {
                    htmlFiles.push(path.join(inputPath, file));
                }
            }
        } else if (inputPath.endsWith('.html') || inputPath.endsWith('.htm')) {
            htmlFiles.push(inputPath);
        }
    } catch (error) {
        console.error(`Error reading path ${inputPath}: ${error.message}`);
    }
    
    return htmlFiles;
}

// Capture screenshot of an HTML file
async function captureScreenshot(browser, htmlFile, outputDir) {
    const context = await browser.newContext({
        viewport: { width: 1280, height: 720 }
    });
    
    const page = await context.newPage();
    
    try {
        // Load the HTML file
        const htmlPath = path.resolve(htmlFile);
        await page.goto(`file://${htmlPath}`);
        
        // Wait for the page to be fully loaded
        await page.waitForLoadState('networkidle');
        
        // Generate output filename
        const basename = path.basename(htmlFile, path.extname(htmlFile));
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-').substring(0, 19);
        const screenshotFilename = `${basename}-${timestamp}.png`;
        const screenshotPath = path.join(outputDir, screenshotFilename);
        
        // Capture full page screenshot
        await page.screenshot({
            path: screenshotPath,
            fullPage: true
        });
        
        console.log(`📸 Screenshot saved: ${screenshotPath}`);
        
        return screenshotPath;
    } catch (error) {
        console.error(`❌ Error capturing screenshot for ${htmlFile}:`, error.message);
        throw error;
    } finally {
        await context.close();
    }
}

// Main function
async function main() {
    const args = parseArgs();
    
    if (args.help) {
        showHelp();
        return;
    }
    
    console.log('🎭 HTML Report Screenshot Automation Tool\n');
    
    // Generate sample report if --test flag is provided
    if (args.test) {
        console.log('📝 Generating sample report...');
        const sampleFile = generateSampleReport();
        args.input = sampleFile;
    }
    
    // Ensure input path exists
    if (!fs.existsSync(args.input)) {
        console.error(`❌ Error: Input path does not exist: ${args.input}`);
        process.exit(1);
    }
    
    // Create output directory if it doesn't exist
    if (!fs.existsSync(args.output)) {
        fs.mkdirSync(args.output, { recursive: true });
        console.log(`📁 Created output directory: ${args.output}`);
    }
    
    // Get HTML files to process
    const htmlFiles = getHtmlFiles(args.input);
    
    if (htmlFiles.length === 0) {
        console.error(`❌ Error: No HTML files found in: ${args.input}`);
        process.exit(1);
    }
    
    console.log(`📄 Found ${htmlFiles.length} HTML file(s) to process\n`);
    
    // Launch browser - try to use system browser if available
    let browser;
    try {
        // Try platform-specific browser paths
        let browserPath = null;
        
        if (process.platform === 'linux') {
            // Linux paths
            const linuxPaths = ['/usr/bin/chromium', '/usr/bin/chromium-browser', '/usr/bin/google-chrome'];
            for (const p of linuxPaths) {
                if (fs.existsSync(p)) {
                    browserPath = p;
                    break;
                }
            }
        } else if (process.platform === 'darwin') {
            // macOS paths
            const macPaths = [
                '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
                '/Applications/Chromium.app/Contents/MacOS/Chromium'
            ];
            for (const p of macPaths) {
                if (fs.existsSync(p)) {
                    browserPath = p;
                    break;
                }
            }
        } else if (process.platform === 'win32') {
            // Windows paths
            const winPaths = [
                'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
                'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
                process.env.LOCALAPPDATA + '\\Google\\Chrome\\Application\\chrome.exe'
            ];
            for (const p of winPaths) {
                if (fs.existsSync(p)) {
                    browserPath = p;
                    break;
                }
            }
        }
        
        if (browserPath) {
            browser = await chromium.launch({ executablePath: browserPath });
        } else {
            // Fall back to Playwright's bundled browser
            browser = await chromium.launch();
        }
    } catch (error) {
        console.log('Using Playwright bundled browser...');
        browser = await chromium.launch();
    }
    
    try {
        // Process each HTML file
        for (const htmlFile of htmlFiles) {
            console.log(`Processing: ${path.basename(htmlFile)}`);
            await captureScreenshot(browser, htmlFile, args.output);
        }
        
        console.log(`\n✅ Successfully processed ${htmlFiles.length} file(s)`);
        console.log(`📸 Screenshots saved to: ${args.output}`);
    } catch (error) {
        console.error('❌ Error:', error.message);
        process.exit(1);
    } finally {
        await browser.close();
    }
}

// Run the script
if (require.main === module) {
    main().catch(error => {
        console.error('Fatal error:', error);
        process.exit(1);
    });
}

module.exports = { captureScreenshot, generateSampleReport };
